# Joseph S. Wirth, 2023
## provides a conda environment for running the python scripts found in this folder
## commands:
##        $ conda env create -f environment.yml
##        $ conda activate misc-python

name: primerforge
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - pip=23.0.1
  - biopython=1.81
  - numpy
  - matplotlib==3.7.2
  - scipy==1.10.1

