# Joseph S. Wirth, 2024
## provides a conda environment for running primerForge
## commands:
##        $ conda env create -f environment.yml
##        $ conda activate primerforge

name: primerforge
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9,<3.12
  - pip=23.0.1
  - biopython=1.81
  - ispcr
  - numpy
  - primer3-py>=2.0
  - pyahocorasick>=2.1
  - scipy>=1.10
  - pip:
      - khmer>=2.1
