# Joseph S. Wirth, 2024
## provides a conda environment for running primerForge
## commands:
##        $ conda env create -f environment.yml
##        $ conda activate primerforge

name: primerforge
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - pip=23.0.1
  - biopython=1.81
  - matplotlib=3.7.2
  - numpy
  - primer3-py>=2.0
  - scipy>=1.10
