[project]
authors = ["Joe Wirth"]
channels = ["conda-forge", "bioconda"]
description = "PrimerForge"
name = "primerforge"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9,<3.12"
ispcr = "*"
scipy = ">=1.10"

[pypi-dependencies]
primerforge = ">=0.1.0"

[system-requirements]
linux = "3"
libc = { family = "glibc", version = "2.0" }
