on: push
name: basic python

jobs:
  example-1:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda env list
        shell: bash -el {0}
        run: |
          conda env list
          conda list
      - name: basic usage
        shell: bash -el {0}  
        run: |
          which python
          python primerForge.py --help
          python primerForge.py --check_install
      - name: pip installation
        shell: bash -el {0}
        run: |
          pip install .
          primerForge --help
          primerForge --check_install
      - name: unit tests
        shell: bash -el {0}
        run: |
          python -m unittest discover -s ./bin/unit_tests/ -p "*_test.py"
      - name: upload pickles
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pickles
          path: test_dir/_pickles/*.p
